### ISSUE TITLE
issue from WP 5.6

### ISSUE THREAD

**Issue by mplusb** [WPChill/final-tiles-grid-gallery-lite#25]
Users with this issue: https://wordpress.org/support/topic/unable-to-edit-galleries-thumbnails-not-visible-in-editor/

I was able to replicate it on my end as well.
When you open the gallery you are unable to see the images there, screenshot: 
<img width="1393" alt="Screenshot 2021-01-11 at 15 15 13" src="https://user-images.githubusercontent.com/26008574/104186976-ddfd0c80-541f-11eb-8508-d0391e2c0455.png">

If you add a new image, they will appear. However, if you edit the gallery again the issue happens again.

**Comment by mplusb** [comment]
tested with the theme Twenty Twenty-One & WP 5.6

**Comment by claudedunn** [comment]
same issue with 5.6 on two different site, tested with healthtest plug-in and twenty-one theme,

**Comment by cheryl2u** [comment]
Any update on this? I'm experiencing the same issue.

**Comment by Zooip** [comment]
Same issue, and I don't know if it's related but every time I edit the images list, all my setting are reset

**Comment by gofreee** [comment]
If you have access to the source codes of your wordpress/plugins, you can easily fix this problem by yourself. However if the author of the plugin updates it, you will lose your changes. My "solution" should be considered quick & dirty.

Locate the **init** function in the following file:
https://github.com/WPChill/final-tiles-grid-gallery-lite/blob/21a127a5ca779462426360fe874129bd48a82b14/admin/scripts/final-tiles-gallery-admin.js#L1016-L1028

Add new line after the line 1020 with the following code: ```FTG.load_images();``` so you end up with this:
```
...
    $imageList = $("#image-list");
    FTG.load_images();
    setInterval(function() {
...
```
DONE! Your images should now load correctly after opening the gallery for editing.

**Note**: It seems that the development of the plugin has moved from github to [plugins.trac.wordpress.org](https://plugins.trac.wordpress.org/browser/final-tiles-grid-gallery-lite/). Version of the plugin on github is 3.4.17 but on wordpress it's a more recent version 3.4.22. [For the version 3.4.22 the **init** function starts at line 1020](https://plugins.trac.wordpress.org/browser/final-tiles-grid-gallery-lite/tags/3.4.22/admin/scripts/final-tiles-gallery-admin.js#L1020) and you should add the new code after line 1024.

**Comment by Scribbles10221** [comment]
I am having the same problem with Final Tiles Gallery - opening an existing gallery with images does not display the images. The "workaround" discussed in another thread, adding an additional image, does trigger all images to display, including the added one. I added the code by gofreee noted above - so far, it has had no impact. I am going to check this again tomorrow morning as there are instances when the update to the website does not take immediately - because GoDaddy has virtual hosting on multiple servers, and I am not convinced that the updates go out to all of the web servers "instantaneously". We will see. Definitely a bug, which just showed up on my website within the last month.

**Comment by SGBPRG** [comment]
I am having the same problem now with FTG 3.5.1. Please update.  I am beginning to think this is deliberate and only fixable by upgrading to premium. That wouldn't be cool.

**Comment by razvanaldea89** [comment]
Tested with Firefox, Edge and Chrome, on localhost and live server, from Windows and Mac OS and everything seems to work OK with the launched version ( 3.5.1 ) from WordPress. Is this still happening?
